apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniweb
  template:
    metadata:
      labels:
        app: miniweb
    spec:
      containers:
        - name: miniweb
          image: miniweb@sha256:0123456789
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
